apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tak-server.fullname" . }}-tak-data
  labels:
    {{- include "tak-server.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.takData.storage.storageClass }}
  storageClassName: {{ .Values.takData.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.takData.storage.size }}
